import { Download, RefreshCw } from "lucide-react";
import Button from "../../components/common/Button";
import Card from "../../components/common/Card";
import CommissionChart from "../../components/commission/CommissionChart";
import CommissionHistory from "../../components/commission/CommissionHistory";
import CommissionStatsCard from "../../components/commission/CommissionStatsCard";
import AuditLogTable from "../../components/commission/AuditLogTable";

const formatMoney = (value) => `${Number(value || 0).toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 })} LKR`;
const formatDate = (value) => value ? new Date(value).toLocaleString() : "-";

export default function CommissionOverview({ dashboard, history, audit, loading, error, onRetry, onRecordTransaction }) {
  if (loading) return <Card className="commission-state"><RefreshCw size={20} className="commission-state__spin" /><h2>Loading commission data</h2><p>Reading current policy and earnings from the commission service.</p></Card>;
  if (error) return <Card className="commission-state commission-state--error"><h2>Commission data unavailable</h2><p>{error}</p><Button variant="outline" leftIcon={<RefreshCw size={15} />} onClick={onRetry}>Retry</Button></Card>;
  const metrics = dashboard || {};
  const categoryDistribution = Object.entries(metrics.categoryDistribution || {});
  const recentHistory = (history || metrics.recentHistory || []).map((entry) => ({ ...entry, bookingAmount: formatMoney(entry.bookingAmount), commissionAmount: formatMoney(entry.commissionAmount), date: formatDate(entry.date) }));
  const auditEntries = (audit || []).map((entry) => ({ ...entry, timestamp: formatDate(entry.timestamp) }));
  return <><div className="commission-stats"><CommissionStatsCard label="Total commission revenue" value={formatMoney(metrics.totalRevenue)} detail="Recorded commission revenue" /><CommissionStatsCard label="Active commission rules" value={metrics.activeRules || 0} detail="Policy rules in effect" tone="blue" /><CommissionStatsCard label="Average commission rate" value={`${Number(metrics.averageRate || 0).toFixed(2)}%`} detail="Revenue / gross booking volume" tone="purple" /><CommissionStatsCard label="Pending settlements" value={formatMoney(metrics.pendingSettlements)} detail="Pending transaction records" tone="amber" /></div><div className="commission-dashboard-grid"><Card className="commission-panel commission-panel--chart"><div className="commission-panel__heading"><div><h2>Commission revenue trend</h2><p>Recorded marketplace commission revenue</p></div><span className="commission-data-label">API data</span></div><CommissionChart values={(metrics.revenueTrend || []).map((point) => Number(point.value || point))} /></Card><Card className="commission-panel"><div className="commission-panel__heading"><div><h2>Category distribution</h2><p>Share of recorded commission revenue</p></div></div>{categoryDistribution.length ? <div className="category-list">{categoryDistribution.map(([category, value]) => <span key={category}><i className="category-dot category-dot--green" />{category}<strong>{value}%</strong></span>)}</div> : <p className="commission-empty">No category transactions recorded yet.</p>}</Card></div><div className="commission-dashboard-grid commission-dashboard-grid--tables"><Card className="commission-panel"><div className="commission-panel__heading"><div><h2>Recent commission history</h2><p>Immutable transaction snapshots</p></div><button className="commission-link" onClick={() => window.print()}><Download size={14} /> Export</button></div>{recentHistory.length ? <CommissionHistory entries={recentHistory} /> : <p className="commission-empty">No commission transactions recorded yet.</p>}</Card><Card className="commission-panel"><div className="commission-panel__heading"><div><h2>Audit log</h2><p>Append-only policy activity</p></div></div>{auditEntries.length ? <AuditLogTable entries={auditEntries} /> : <p className="commission-empty">No audit activity recorded yet.</p>}</Card></div></>;
}
