export const initialCustomerProfile = {
  id: "CUST-98421",
  fullName: "Kasun Perera",
  preferredName: "Kasun",
  email: "kasun.perera@example.com",
  phone: "+94 77 123 4567",
  avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80",
  memberSince: "March 2024",
  bio: "Homeowner in Colombo 07. Frequently looking for trusted electrical, plumbing, and garden maintenance services on ClickCart.",
  location: "Colombo, Western Province, Sri Lanka",
  dateOfBirth: "1994-06-18",
  gender: "Male",
  preferredLanguage: "English (UK)",
  defaultCurrency: "LKR (Rs.)",
  timezone: "Asia/Colombo (GMT+5:30)",
  emergencyContact: "+94 71 987 6543 (Wife - Nimalee)",
  
  verification: {
    status: "Verified",
    level: "Level 2 Verified Customer",
    badgeLabel: "Verified Customer",
    nationalIdVerified: true,
    emailVerified: true,
    phoneVerified: true,
    paymentMethodVerified: true,
    verifiedDate: "April 12, 2024",
  },

  stats: {
    totalBookings: 24,
    activeOrders: 2,
    completedServices: 22,
    favoriteProviders: 8,
    loyaltyPoints: 1450,
    totalSaved: "Rs. 18,500",
  },

  savedAddresses: [
    {
      id: "addr-1",
      label: "Home (Primary)",
      type: "Home",
      recipientName: "Kasun Perera",
      phone: "+94 77 123 4567",
      addressLine1: "No. 45/2, Guildford Crescent",
      addressLine2: "Apt 4B, Cinnamon Gardens",
      city: "Colombo 07",
      postalCode: "00700",
      province: "Western Province",
      country: "Sri Lanka",
      isDefault: true,
      notes: "Ring the buzzer for Apt 4B. Parking available near security post.",
    },
    {
      id: "addr-2",
      label: "Office / Workspace",
      type: "Office",
      recipientName: "Kasun Perera (TechCorp HQ)",
      phone: "+94 11 234 5678",
      addressLine1: "Level 14, World Trade Center",
      addressLine2: "Echelon Square",
      city: "Colombo 01",
      postalCode: "00100",
      province: "Western Province",
      country: "Sri Lanka",
      isDefault: false,
      notes: "Deliver to 14th floor reception during standard business hours (9 AM - 5 PM).",
    },
    {
      id: "addr-3",
      label: "Holiday Villa",
      type: "Other",
      recipientName: "Kasun Perera / Villa Caretaker",
      phone: "+94 91 223 4455",
      addressLine1: "No. 12, Beach Road",
      addressLine2: "Thalpe",
      city: "Galle",
      postalCode: "80000",
      province: "Southern Province",
      country: "Sri Lanka",
      isDefault: false,
      notes: "Contact caretaker Sunil 30 minutes prior to arrival.",
    },
  ],

  recentActivities: [
    {
      id: "act-1",
      title: "AC Servicing & Master Filter Clean",
      provider: "CoolBreeze Air Conditioning Ltd.",
      date: "Yesterday at 3:30 PM",
      status: "In Progress",
      statusVariant: "warning",
      amount: "Rs. 4,500",
      iconType: "service",
    },
    {
      id: "act-2",
      title: "Emergency Plumbing Repair",
      provider: "QuickFix Plumbers Sri Lanka",
      date: "Sep 15, 2026",
      status: "Completed",
      statusVariant: "success",
      amount: "Rs. 6,800",
      ratingGiven: 5,
      iconType: "service",
    },
    {
      id: "act-3",
      title: "Earned 250 ClickCart Loyalty Points",
      provider: "ClickCart Rewards Club",
      date: "Sep 15, 2026",
      status: "Credited",
      statusVariant: "info",
      amount: "+250 pts",
      iconType: "reward",
    },
    {
      id: "act-4",
      title: "Landscape & Lawn Trimming",
      provider: "GreenThumb Gardeners",
      date: "Aug 28, 2026",
      status: "Completed",
      statusVariant: "success",
      amount: "Rs. 8,000",
      ratingGiven: 4.8,
      iconType: "service",
    },
  ],
};
