package com.clickcart.model;

public enum NotificationType {
    NEW_BOOKING_REQUEST,
    BOOKING_CONFIRMED,
    BOOKING_CANCELLED,
    UPCOMING_BOOKING_REMINDER,
    PAYMENT_RECEIVED,
    COMMISSION_DEDUCTED,
    REFUND_ISSUED,
    NEW_MESSAGE,
    NEW_REVIEW_POSTED,
    REVIEW_MODERATION_ALERT,
    PROFILE_VERIFICATION_UPDATES,
    PLATFORM_ANNOUNCEMENTS
}
