spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: clickcart-backend
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb+srv://Admin:ABC123@cluster0.2ndv7.mongodb.net/Clickcart_db?authSource=admin&retryWrites=true&w=majority&appName=Cluster0}

server:
  port: ${SERVER_PORT:8080}

CLOUDINARY_CLOUD_NAME: p9vv6uqp
CLOUDINARY_API_KEY: "375111711487698"
CLOUDINARY_API_SECRET: "PIYm_qC1JFXSTWaK_q0cqooSuZQ"