spring:
  application:
    name: clickcart-backend
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/clickcart}

server:
  port: ${SERVER_PORT:8080}

CLOUDINARY_CLOUD_NAME: p9vv6uqp
CLOUDINARY_API_KEY: "375111711487698"
CLOUDINARY_API_SECRET: "PIYm_qC1JFXSTWaK_q0cqooSuZQ"